name: Run mypy and ruff

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Run dependency libraries
        run: |
          pip install -e .
          pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0
          pip install mypy ruff

      - name: Run mypy
        run: find lighthouse -type f -name "*.py" -not -path 'lighthouse/common/*' | xargs mypy

      - name: Run ruff
        run: find lighthouse -type f -name "*.py" -not -path 'lighthouse/common/*' | xargs -I {} sh -c 'ruff check "{}"'
