name: Run pytest

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Run ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y ffmpeg

      - name: Run dependency libraries
        run: |
          pip install -e .
          pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 torchtext==0.16.0
          pip install pytest
      - name: Run pytest
        run: pytest tests/test_models.py
